server:
  port: 5050
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  jasypt:
    encryptor:
      algorithm: PBEWithMD5AndTripleDES
      iv-generator-classname: org.jasypt.iv.NoIvGenerator
      password: ${JASYPT_ENCRYPTOR_PASSWORD}
  datasource:
    url: ENC(fnmW4bsl0cHbwOMMjwDlglEmlcfq0Ul1ed+qvW81dEXjkWn5MXtp5M1+M98YEwo3t5ag6WfqkdNPCR8rEKvDXxduble3Y3rRTSMLHwzsojeU4/phBjBINNVDDoD0bSwO)
    username: ENC(/IJKLGCyENilB91R4+VZQ4Ff1BnXfMbx9U81ONY3ShKRp8zPSgioENEmGjE9kRujMckxl5Fw4SQQU6zG/QLv9Q==)
    password: ENC(WWTrnU4VXnXhLEHjZLo2gXP5Z031HlujQE1tvItLSTijrnrhvEcfDCjwB0NfATonlIX0D4RTlSirCTPsUGdJPQ==)
  graphql:
    servlet:
      enabled: true
      mapping: /graphql
      cors-enabled: true
      cors:
        allowed-origins: http://localhost:5050
        allowed-methods: GET, HEAD, POST
      async-mode-enabled: true
    graphiql:
      enabled: true
